import { Layout } from "@/components/layout";
import { motion } from "framer-motion";

const sections = [
  {
    title: "1. Introduction",
    body: `RunWars ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use the RunWars mobile application and website (collectively, the "App"). By using RunWars, you consent to the practices described in this policy.`,
  },
  {
    title: "2. Information We Collect",
    body: `We collect information you provide directly (such as account registration details, username, and email address), information generated by your use of the App (including GPS location data, movement activity, territory captures, gameplay statistics, and device identifiers), and technical data (such as IP address, device type, operating system, and crash reports).`,
  },
  {
    title: "3. Location Data",
    body: `RunWars is a GPS-based game. We collect precise real-time location data while the App is in use to enable gameplay features such as hex capture, territory mapping, and conflict notifications. Location data is processed to generate game events and is stored in anonymized form for leaderboard and analytics purposes. You may disable location access in your device settings, but this will prevent core gameplay functionality.`,
  },
  {
    title: "4. How We Use Your Information",
    body: `We use your information to: provide and operate the App and its features; process in-game events and maintain accurate territory records; communicate with you about gameplay, account activity, and service updates; analyze usage patterns to improve the App; detect and prevent fraud, cheating, and abuse; and comply with applicable legal obligations.`,
  },
  {
    title: "5. Sharing of Information",
    body: `We do not sell your personal information. We may share your data with trusted service providers who assist in operating the App (such as cloud hosting and analytics providers), subject to strict confidentiality obligations. We may disclose information when required by law, court order, or government authority. Aggregated, anonymized data may be shared publicly (e.g., city-level territory statistics).`,
  },
  {
    title: "6. Data Retention",
    body: `We retain your personal data for as long as your account is active or as needed to provide you services. You may request deletion of your account and associated data at any time by contacting privacy@runwars.app. Anonymized gameplay data may be retained indefinitely for analytical and historical purposes.`,
  },
  {
    title: "7. Security",
    body: `We implement industry-standard security measures to protect your information, including encryption in transit (TLS) and at rest, access controls, and regular security audits. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.`,
  },
  {
    title: "8. Children's Privacy",
    body: `RunWars is not directed at children under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided us with personal information, we will promptly delete such information. Parents or guardians who believe their child has submitted data should contact us at privacy@runwars.app.`,
  },
  {
    title: "9. Your Rights",
    body: `Depending on your jurisdiction, you may have the right to access, correct, delete, or restrict processing of your personal data. You may also have the right to data portability and to withdraw consent at any time. To exercise these rights, contact us at privacy@runwars.app. We will respond within 30 business days.`,
  },
  {
    title: "10. Third-Party Services",
    body: `The App may integrate with third-party platforms (such as app stores, analytics providers, and payment processors). These third parties have their own privacy policies. RunWars is not responsible for the privacy practices of third-party services. We encourage you to review their policies.`,
  },
  {
    title: "11. Cookies & Tracking",
    body: `Our website may use cookies and similar tracking technologies to improve user experience and analyze site traffic. You can control cookie settings through your browser. Disabling cookies may affect certain website functionality but does not impact in-App gameplay.`,
  },
  {
    title: "12. Changes to This Policy",
    body: `We may update this Privacy Policy periodically. We will notify you of material changes via the App or by email. Your continued use of RunWars after changes are posted constitutes your acceptance of the updated policy. We encourage you to review this policy regularly.`,
  },
  {
    title: "13. Contact Us",
    body: `If you have any questions, concerns, or requests regarding this Privacy Policy, please contact our Privacy Team at: privacy@runwars.app. RunWars takes all privacy inquiries seriously and is committed to resolving them promptly and transparently.`,
  },
];

export default function Privacy() {
  return (
    <Layout>
      <div className="container mx-auto px-4 py-20 max-w-3xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <p className="text-xs font-mono text-muted-foreground uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-4xl md:text-6xl font-bold uppercase tracking-tighter mb-4">Privacy Policy</h1>
          <p className="text-muted-foreground font-mono text-sm">
            Effective date: January 1, 2025 &mdash; All rights reserved &copy; RunWars
          </p>
        </motion.div>

        <div className="space-y-10">
          {sections.map((section, i) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.04 }}
              className="border-b border-border pb-10 last:border-0"
            >
              <h2 className="text-lg font-bold uppercase tracking-wider mb-3 text-primary">{section.title}</h2>
              <p className="text-muted-foreground font-mono text-sm leading-relaxed">{section.body}</p>
            </motion.div>
          ))}
        </div>

        <div className="mt-16 p-6 bg-card border border-border rounded-xl font-mono text-xs text-muted-foreground">
          &copy; {new Date().getFullYear()} RunWars. All rights reserved. Your privacy matters to us — RunWars is built on trust.
        </div>
      </div>
    </Layout>
  );
}
